// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'music/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `global_playback_session`, `open_scan_conn`, `open_stats_conn`, `parse_headers_json`, `parse_remote_source`, `parse_song_path_sort_mode`

/// 对一整块 QMC 加密音频字节做解密，返回解密后的字节。
/// `ekey` 为 base64 编码的 QMC2 key（EncV2 已自动处理）。
Future<Uint8List> qmcDecryptBytes({
  required List<int> data,
  required String ekey,
}) => RustLib.instance.api.crateApiQmcDecryptBytes(data: data, ekey: ekey);

/// 将 PCM 采样划分成指定数量的频带，返回每个频带的归一化能量。
Future<Float32List> spectrumBands({
  required List<double> samples,
  required int sampleRate,
  required BigInt bandCount,
}) => RustLib.instance.api.crateApiSpectrumBands(
  samples: samples,
  sampleRate: sampleRate,
  bandCount: bandCount,
);

/// 对一块交错 PCM 应用音效 DSP 链。
///
/// - `samples`：交错 PCM（样本数应为 `channels` 的整数倍）
/// - `sample_rate`：采样率
/// - `channels`：声道数（1 或 2）
/// - `settings_json`：[`SoundEffectSettings`] 的 JSON（camelCase，可部分省略）
///
/// 返回处理后的交错 PCM。变调变速时输出样本数可能 ≠ 输入。
/// 所有音效关闭（含默认）时为无损直通。状态在单次调用内保持。
Future<Float32List> soundEffectProcess({
  required List<double> samples,
  required int sampleRate,
  required int channels,
  required String settingsJson,
}) => RustLib.instance.api.crateApiSoundEffectProcess(
  samples: samples,
  sampleRate: sampleRate,
  channels: channels,
  settingsJson: settingsJson,
);

/// 解析原始歌词文本（LRC/YRC/QRC/ESLRC/TTML/Lys 等），
/// 返回 [`StructuredLyricsPayload`] 的 JSON（camelCase）。
///
/// 包含 `document`（解析出的多轨结构）、`semanticLines`（语义行）和
/// `displayLines`（可直接用于逐行/逐字播放的展示行，含 translation/romaji）。
/// 解析失败或空文本时返回合法 JSON 结构而非错误。
Future<String> parseLyrics({required String rawLyrics}) =>
    RustLib.instance.api.crateApiParseLyrics(rawLyrics: rawLyrics);

/// 解析 LX 音源播放直链。
///
/// - `song_info_json`：[`LxUrlSongInfo`] 的 JSON（camelCase）
/// - `quality`：音质（如 "128k"、"320k"、"flac" 等）
///
/// 返回 [`ResolvedUrl`] 的 JSON；解析失败返回 `"null"`。
Future<String> lxResolveUrl({
  required String songInfoJson,
  required String quality,
}) => RustLib.instance.api.crateApiLxResolveUrl(
  songInfoJson: songInfoJson,
  quality: quality,
);

/// 获取 LX 音源封面 URL，返回 URL 字符串；无封面返回 `#optional#` 空值。
Future<String?> lxGetCover({required String songInfoJson}) =>
    RustLib.instance.api.crateApiLxGetCover(songInfoJson: songInfoJson);

/// 搜索音乐源。`source` ∈ `kw`/`kg`/`tx`/`wy`/`mg`。
/// 返回 [`LxSearchItem`] 数组的 JSON；失败返回错误信息。
Future<String> lxSearch({
  required String source,
  required String keyword,
  required int limit,
}) => RustLib.instance.api.crateApiLxSearch(
  source: source,
  keyword: keyword,
  limit: limit,
);

/// 清除 LX 缓存（URL + 搜索）。
Future<void> lxClearCache() => RustLib.instance.api.crateApiLxClearCache();

/// 从指定音源抓取歌词（kg/kw/tx/wy）。
///
/// - `song_info_json`：[
/// `LyricSongInfo`] 的 JSON（camelCase）
///
/// 返回 [`LyricResult`]（含 lyric/tlyric/rlyric/lxlyric）的 JSON；
/// 该音源无歌词返回 `"null"`。
Future<String> fetchLyricFromSource({
  required String source,
  required String songInfoJson,
}) => RustLib.instance.api.crateApiFetchLyricFromSource(
  source: source,
  songInfoJson: songInfoJson,
);

/// 为在线音频 URL 创建流式缓存并启动后台下载。
///
/// - `headers_json`：可选 HTTP 头 JSON（对象，如 `{"Referer": "..."}`）
/// - `ekey`：可选 QMC2 加密 key（base64）
///
/// 返回缓存文件路径的 JSON（`{"path": "...", "downloadedBytes": n, "finished": bool}`）。
Future<String> startStreamingDownload({
  required String url,
  required String headersJson,
  String? userAgent,
  String? ekey,
}) => RustLib.instance.api.crateApiStartStreamingDownload(
  url: url,
  headersJson: headersJson,
  userAgent: userAgent,
  ekey: ekey,
);

/// 检查指定 URL 是否已缓存且下载完成。
Future<bool> isUrlCached({required String url}) =>
    RustLib.instance.api.crateApiIsUrlCached(url: url);

/// 等待指定 URL 缓存下载完成（超时秒数）。
Future<bool> waitUrlComplete({
  required String url,
  required BigInt timeoutSecs,
}) => RustLib.instance.api.crateApiWaitUrlComplete(
  url: url,
  timeoutSecs: timeoutSecs,
);

/// 清理所有流缓存。
Future<void> clearStreamCache() =>
    RustLib.instance.api.crateApiClearStreamCache();

/// 读取音频文件的文本元数据（标题/歌手/专辑/专辑歌手）。
///
/// 返回 camelCase JSON：
/// `{"title":"...","artist":"...","album":"...","albumArtist":"..."}`。
Future<String> readAudioMetadata({required String filePath}) =>
    RustLib.instance.api.crateApiReadAudioMetadata(filePath: filePath);

/// 将元数据写入音频文件的 tag（ID3v2/Vorbis Comment/MP4 Atom 等）。
///
/// 仅写入请求中提供的非空字段，其余保持不变；无现有 tag 时按扩展名创建。
/// 请求为 camelCase JSON，可含：
/// `filePath`(必填)、`title`/`artist`/`album`/`albumArtist`/`year`/
/// `trackNumber`/`discNumber`(`String`)、`lyrics`(`String`)、
/// `coverData`(`Vec<u8>`)+`coverMime`(`String`)。
Future<void> writeAudioMetadata({required String requestJson}) =>
    RustLib.instance.api.crateApiWriteAudioMetadata(requestJson: requestJson);

/// 列出 WebDAV 目录内容。
///
/// - `source_json`：WebDAV 源凭据（camelCase，含 `baseUrl`/`username`/`password`/`rootPath`）
/// - `path`：远程目录路径（如 `/` 或 `/专辑`）
///
/// 返回 [`RemoteFileEntry`] 数组的 JSON（camelCase，含 `remotePath`/`name`/`size`/`isDir`）。
Future<String> webdavListDirectory({
  required String sourceJson,
  required String path,
}) => RustLib.instance.api.crateApiWebdavListDirectory(
  sourceJson: sourceJson,
  path: path,
);

/// 测试 WebDAV 连接（列出根目录）。
Future<void> webdavTestConnection({required String sourceJson}) =>
    RustLib.instance.api.crateApiWebdavTestConnection(sourceJson: sourceJson);

/// 递归扫描 WebDAV 源下的所有音频文件。
///
/// 返回 [`RemoteFileEntry`] 数组的 JSON（仅音频文件，不含目录）。
Future<String> webdavCollectAudioFiles({required String sourceJson}) => RustLib
    .instance
    .api
    .crateApiWebdavCollectAudioFiles(sourceJson: sourceJson);

/// 从 WebDAV 断点续传下载文件到本地路径。
///
/// 目标文件已存在部分字节时从断点继续（RANGE 请求）。
Future<void> webdavDownloadFile({
  required String sourceJson,
  required String remotePath,
  required String targetPath,
}) => RustLib.instance.api.crateApiWebdavDownloadFile(
  sourceJson: sourceJson,
  remotePath: remotePath,
  targetPath: targetPath,
);

/// 提取音频文件内置的 ReplayGain 标签。
///
/// 返回 JSON `{"gainDb": <f32>, "peakDb": <f32>|null}`；无标签返回 `"null"`。
Future<String> extractReplaygain({required String filePath}) =>
    RustLib.instance.api.crateApiExtractReplaygain(filePath: filePath);

/// 计算实际应用的播放增益（Linear Gain 倍数）。
///
/// - `record_json`：[`LoudnessRecord`] 的 JSON（camelCase）
/// - `gain_offset_db`：用户手动增益偏移（dB）
/// - `prevent_clipping`：是否启用破音保护
Future<double> loudnessCalculatePlaybackGain({
  required String recordJson,
  required double gainOffsetDb,
  required bool preventClipping,
}) => RustLib.instance.api.crateApiLoudnessCalculatePlaybackGain(
  recordJson: recordJson,
  gainOffsetDb: gainOffsetDb,
  preventClipping: preventClipping,
);

/// 记录一次播放事件（含聚合统计与播放历史）。
///
/// - `db_path`：SQLite 数据库文件路径
/// - `payload_json`：[`RecordPlayPayload`] 的 JSON（camelCase，如
///   `{"songPath":"...","listenedMs":30000,"durationMs":195000,"title":"...","artist":"..."}`）
Future<void> statsRecordPlay({
  required String dbPath,
  required String payloadJson,
}) => RustLib.instance.api.crateApiStatsRecordPlay(
  dbPath: dbPath,
  payloadJson: payloadJson,
);

/// 获取三个周期的听歌时长（日/周/总），返回 JSON 秒数。
Future<String> statsGetListenDurations({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsGetListenDurations(dbPath: dbPath);

/// 获取行为统计（Top 歌曲/歌手/专辑、时段分布、近期活跃）。
///
/// - `time_range_json`：[`TimeRange`] 的 JSON（如 `{"type":"Days30"}`）
Future<String> statsGetBehaviorStats({
  required String dbPath,
  required String timeRangeJson,
}) => RustLib.instance.api.crateApiStatsGetBehaviorStats(
  dbPath: dbPath,
  timeRangeJson: timeRangeJson,
);

/// 获取曲库统计（歌曲/专辑/歌手数、总时长、无损比例等）。
Future<String> statsGetLibraryStats({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsGetLibraryStats(dbPath: dbPath);

/// 获取文件格式分布。
Future<String> statsGetFormatDistribution({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsGetFormatDistribution(dbPath: dbPath);

/// 获取音质分布（Hi-Res / 无损 / 高码率 / 其他）。
Future<String> statsGetQualityDistribution({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsGetQualityDistribution(dbPath: dbPath);

/// 获取最近播放历史（去重，按播放时间倒序）。
Future<String> statsGetRecentHistory({required String dbPath, BigInt? limit}) =>
    RustLib.instance.api.crateApiStatsGetRecentHistory(
      dbPath: dbPath,
      limit: limit,
    );

/// 添加一条最近播放记录。
Future<void> statsAddToHistory({
  required String dbPath,
  required String songPath,
}) => RustLib.instance.api.crateApiStatsAddToHistory(
  dbPath: dbPath,
  songPath: songPath,
);

/// 清空最近播放历史。
Future<void> statsClearRecentHistory({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsClearRecentHistory(dbPath: dbPath);

/// 重置所有本地听歌统计（含播放历史与聚合统计）。
Future<void> statsResetLocalStatistics({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsResetLocalStatistics(dbPath: dbPath);

/// 批量导入最近播放历史。
///
/// - `entries_json`：[`RecentHistoryImportEntry`] 数组的 JSON（camelCase）
Future<void> statsImportRecentHistory({
  required String dbPath,
  required String entriesJson,
}) => RustLib.instance.api.crateApiStatsImportRecentHistory(
  dbPath: dbPath,
  entriesJson: entriesJson,
);

/// 从最近播放/收藏路径构建歌手目录。
Future<String> statsGetFavoriteArtistCatalog({
  required String dbPath,
  required List<String> favoritePaths,
}) => RustLib.instance.api.crateApiStatsGetFavoriteArtistCatalog(
  dbPath: dbPath,
  favoritePaths: favoritePaths,
);

/// 从最近播放/收藏路径构建专辑目录。
Future<String> statsGetFavoriteAlbumCatalog({
  required String dbPath,
  required List<String> favoritePaths,
}) => RustLib.instance.api.crateApiStatsGetFavoriteAlbumCatalog(
  dbPath: dbPath,
  favoritePaths: favoritePaths,
);

/// 从最近播放记录构建最近专辑目录。
Future<String> statsGetRecentAlbumCatalog({
  required String dbPath,
  required String entriesJson,
}) => RustLib.instance.api.crateApiStatsGetRecentAlbumCatalog(
  dbPath: dbPath,
  entriesJson: entriesJson,
);

/// 从收藏路径构建排序后的歌曲路径列表。
///
/// - `sort_mode`：`"title"`/`"artist"`/`"addedAt"`/`"addedAtAsc"`/`"fileModifiedAt"`/`"fileModifiedAtAsc"`
Future<String> statsGetFavoriteSongPathsView({
  required String dbPath,
  required List<String> favoritePaths,
  String? query,
  required String sortMode,
  String? detailFilterType,
  String? detailFilterValue,
}) => RustLib.instance.api.crateApiStatsGetFavoriteSongPathsView(
  dbPath: dbPath,
  favoritePaths: favoritePaths,
  query: query,
  sortMode: sortMode,
  detailFilterType: detailFilterType,
  detailFilterValue: detailFilterValue,
);

/// 从最近播放记录构建排序后的歌曲路径列表。
Future<String> statsGetRecentSongPathsView({
  required String dbPath,
  required String entriesJson,
  String? query,
  required String sortMode,
}) => RustLib.instance.api.crateApiStatsGetRecentSongPathsView(
  dbPath: dbPath,
  entriesJson: entriesJson,
  query: query,
  sortMode: sortMode,
);

/// 从播放列表与最近播放记录构建最近播放列表目录。
Future<String> statsGetRecentPlaylistCatalog({
  required String dbPath,
  required String playlistsJson,
  required String entriesJson,
}) => RustLib.instance.api.crateApiStatsGetRecentPlaylistCatalog(
  dbPath: dbPath,
  playlistsJson: playlistsJson,
  entriesJson: entriesJson,
);

/// 从最近播放历史移除指定歌曲。
Future<void> statsRemoveFromRecentHistory({
  required String dbPath,
  required List<String> songPaths,
}) => RustLib.instance.api.crateApiStatsRemoveFromRecentHistory(
  dbPath: dbPath,
  songPaths: songPaths,
);

/// 从历史与统计中彻底移除指定歌曲。
Future<void> statsRemoveSongsFromHistoryAndStatistics({
  required String dbPath,
  required List<String> songPaths,
}) => RustLib.instance.api.crateApiStatsRemoveSongsFromHistoryAndStatistics(
  dbPath: dbPath,
  songPaths: songPaths,
);

/// 导出统计备份到 JSON 文件。
///
/// - `options_json`：[`StatisticsExportOptions`] 的 JSON（camelCase，含 `filePath`/`includeRecentPlays`）
Future<String> statsExportStatisticsFile({
  required String dbPath,
  required String optionsJson,
}) => RustLib.instance.api.crateApiStatsExportStatisticsFile(
  dbPath: dbPath,
  optionsJson: optionsJson,
);

/// 预览统计备份导入（不写库）。
Future<String> statsPreviewStatisticsImport({
  required String dbPath,
  required String optionsJson,
}) => RustLib.instance.api.crateApiStatsPreviewStatisticsImport(
  dbPath: dbPath,
  optionsJson: optionsJson,
);

/// 导入统计备份。
///
/// - `options_json`：[`StatisticsImportOptions`] 的 JSON（camelCase，
///   含 `filePath`/`mode`("overwrite"|"merge")/`continueDuplicateImport`）
Future<String> statsImportStatisticsFile({
  required String dbPath,
  required String optionsJson,
}) => RustLib.instance.api.crateApiStatsImportStatisticsFile(
  dbPath: dbPath,
  optionsJson: optionsJson,
);

/// 增量扫描一个音乐文件夹，将新增/更新/删除写入数据库，返回该文件夹全部歌曲 JSON。
///
/// - `db_path`：SQLite 数据库文件路径
/// - `folder_path`：要扫描的文件夹路径
/// - `minimum_duration_seconds`：低于该时长的歌曲被过滤（0 表示不过滤）
Future<String> scanMusicFolder({
  required String dbPath,
  required String folderPath,
  int? minimumDurationSeconds,
  List<String>? allowedFormats,
}) => RustLib.instance.api.crateApiScanMusicFolder(
  dbPath: dbPath,
  folderPath: folderPath,
  minimumDurationSeconds: minimumDurationSeconds,
  allowedFormats: allowedFormats,
);

/// 解析指定音频文件路径并返回歌曲（不写库）。
///
/// - `paths_json`：路径数组的 JSON，如 `["/music/a.flac","/music/b.mp3"]`
Future<String> parseAudioFiles({
  required String pathsJson,
  int? minimumDurationSeconds,
}) => RustLib.instance.api.crateApiParseAudioFiles(
  pathsJson: pathsJson,
  minimumDurationSeconds: minimumDurationSeconds,
);

/// 递归解析文件夹内所有受支持音频文件并返回歌曲（不写库）。
Future<String> parseMusicFolder({
  required String folderPath,
  int? minimumDurationSeconds,
}) => RustLib.instance.api.crateApiParseMusicFolder(
  folderPath: folderPath,
  minimumDurationSeconds: minimumDurationSeconds,
);

/// 将歌曲列表按父文件夹分组为播放列表。
///
/// - `songs_json`：歌曲数组的 JSON
Future<String> groupSongsAsPlaylists({required String songsJson}) =>
    RustLib.instance.api.crateApiGroupSongsAsPlaylists(songsJson: songsJson);

/// 查找文件夹内（含子目录）第一首歌曲路径，用于展示封面。
Future<String?> findFirstSongRecursive({
  required String dbPath,
  required String folderPath,
}) => RustLib.instance.api.crateApiFindFirstSongRecursive(
  dbPath: dbPath,
  folderPath: folderPath,
);

/// 递归构建文件夹目录树（含每层歌曲数/封面）。
///
/// - `max_depth`：最大递归深度
Future<String?> scanFolderTree({
  required String dbPath,
  required String folderPath,
  required int maxDepth,
}) => RustLib.instance.api.crateApiScanFolderTree(
  dbPath: dbPath,
  folderPath: folderPath,
  maxDepth: maxDepth,
);

/// 列出全部远程源（返回 [`RemoteSource`] 数组 JSON）。
Future<String> listRemoteSources({required String dbPath}) =>
    RustLib.instance.api.crateApiListRemoteSources(dbPath: dbPath);

/// 新增或更新远程源（按 `RemoteSourceInput` JSON，缺 id 则新增）。
Future<String> saveRemoteSource({
  required String dbPath,
  required String sourceJson,
}) => RustLib.instance.api.crateApiSaveRemoteSource(
  dbPath: dbPath,
  sourceJson: sourceJson,
);

/// 删除远程源及其关联歌曲。
Future<void> removeRemoteSource({
  required String dbPath,
  required String sourceId,
}) => RustLib.instance.api.crateApiRemoveRemoteSource(
  dbPath: dbPath,
  sourceId: sourceId,
);

/// 同步远程源：扫描远程目录、增量解析并写入音乐库。
///
/// - `cache_root`：远程音频缓存根目录（调用方传入 app 缓存目录）
/// - `source_id`：远程源 id
///
/// 返回 [`RemoteSyncResult`] JSON。
Future<String> syncRemoteSource({
  required String dbPath,
  required String cacheRoot,
  required String sourceId,
}) => RustLib.instance.api.crateApiSyncRemoteSource(
  dbPath: dbPath,
  cacheRoot: cacheRoot,
  sourceId: sourceId,
);

/// 查询远程音频缓存占用（返回 [`RemoteCacheUsage`] JSON）。
Future<String> getRemoteCacheUsage({required String cacheRoot}) =>
    RustLib.instance.api.crateApiGetRemoteCacheUsage(cacheRoot: cacheRoot);

/// 清空远程音频缓存（返回清空后 [`RemoteCacheUsage`] JSON）。
Future<String> clearRemoteCache({required String cacheRoot}) =>
    RustLib.instance.api.crateApiClearRemoteCache(cacheRoot: cacheRoot);

/// 解析远程音乐播放来源：已缓存返回本地路径，未缓存返回直链流。
///
/// 返回 `{"kind":"cached","path":...}` 或 `{"kind":"stream","url":...,...}` JSON。
Future<String> remotePlaybackSource({
  required String dbPath,
  required String remoteUri,
}) => RustLib.instance.api.crateApiRemotePlaybackSource(
  dbPath: dbPath,
  remoteUri: remoteUri,
);

/// 预下载远程文件到缓存并回写 `songs.cache_path`。
Future<void> precacheRemoteSong({
  required String dbPath,
  required String cacheRoot,
  required String remoteUri,
}) => RustLib.instance.api.crateApiPrecacheRemoteSong(
  dbPath: dbPath,
  cacheRoot: cacheRoot,
  remoteUri: remoteUri,
);

/// 从封面提取主色调调色板（返回 `["hsl(...)"]` 数组 JSON）。
///
/// `source` 可为本地路径、`http(s)` 直链或 `data:` URI。
/// 纯 CPU 运算，宿主应在后台线程调用。
Future<String> extractPalette({
  required String source,
  required BigInt count,
  required double colorBoost,
  required double depth,
}) => RustLib.instance.api.crateApiExtractPalette(
  source: source,
  count: count,
  colorBoost: colorBoost,
  depth: depth,
);

/// 读取侧边栏文件夹（废弃兼容，返回 `SidebarFolder[]` JSON）。
Future<String> getSidebarFolders({required String dbPath}) =>
    RustLib.instance.api.crateApiGetSidebarFolders(dbPath: dbPath);

/// 新增侧边栏文件夹（废弃兼容）。
Future<void> addSidebarFolder({required String dbPath, required String path}) =>
    RustLib.instance.api.crateApiAddSidebarFolder(dbPath: dbPath, path: path);

/// 删除侧边栏文件夹（废弃兼容）。
Future<void> removeSidebarFolder({
  required String dbPath,
  required String path,
}) => RustLib.instance.api.crateApiRemoveSidebarFolder(
  dbPath: dbPath,
  path: path,
);

/// 侧边栏目录树（废弃兼容，返回 `FolderNode[]` JSON）。
Future<String> getSidebarHierarchy({required String dbPath}) =>
    RustLib.instance.api.crateApiGetSidebarHierarchy(dbPath: dbPath);

/// 向账号 API 发起带签名的 POST 请求（返回响应 JSON）。
Future<String> authAuthedRequest({
  required String dataDir,
  required String action,
  required String bodyJson,
  BigInt? fetchTimeoutMs,
}) => RustLib.instance.api.crateApiAuthAuthedRequest(
  dataDir: dataDir,
  action: action,
  bodyJson: bodyJson,
  fetchTimeoutMs: fetchTimeoutMs,
);

/// 向任意 URL 发起带签名的 POST 请求（壁纸等非账号端点）。
Future<String> authSignedPostJson({
  required String dataDir,
  required String url,
  required String bodyJson,
  BigInt? fetchTimeoutMs,
}) => RustLib.instance.api.crateApiAuthSignedPostJson(
  dataDir: dataDir,
  url: url,
  bodyJson: bodyJson,
  fetchTimeoutMs: fetchTimeoutMs,
);

/// 保存认证凭证（token + user JSON 写入 auth 目录）。
Future<void> authSaveCredentials({
  required String dataDir,
  required String token,
  required String userJson,
}) => RustLib.instance.api.crateApiAuthSaveCredentials(
  dataDir: dataDir,
  token: token,
  userJson: userJson,
);

/// 读取认证凭证（返回 `AuthCredentials` JSON 或 null）。
Future<String> authGetCredentials({required String dataDir}) =>
    RustLib.instance.api.crateApiAuthGetCredentials(dataDir: dataDir);

/// 清除认证凭证。
Future<void> authClearCredentials({required String dataDir}) =>
    RustLib.instance.api.crateApiAuthClearCredentials(dataDir: dataDir);

/// 设置 API 基地址。
Future<void> authSetBaseUrl({
  required String dataDir,
  required String baseUrl,
}) => RustLib.instance.api.crateApiAuthSetBaseUrl(
  dataDir: dataDir,
  baseUrl: baseUrl,
);

/// 获取 API 基地址。
Future<String> authGetBaseUrl({required String dataDir}) =>
    RustLib.instance.api.crateApiAuthGetBaseUrl(dataDir: dataDir);

/// 设置 API 签名密钥。
Future<void> authSetApiSecret({
  required String dataDir,
  required String apiSecret,
}) => RustLib.instance.api.crateApiAuthSetApiSecret(
  dataDir: dataDir,
  apiSecret: apiSecret,
);

/// 获取 API 签名密钥。
Future<String> authGetApiSecret({required String dataDir}) =>
    RustLib.instance.api.crateApiAuthGetApiSecret(dataDir: dataDir);

/// 读取音乐库文件夹（返回 `LibraryFolder[]` JSON，含歌曲数）。
Future<String> getLibraryFolders({required String dbPath}) =>
    RustLib.instance.api.crateApiGetLibraryFolders(dbPath: dbPath);

/// 新增音乐库文件夹。
Future<void> addLibraryFolder({required String dbPath, required String path}) =>
    RustLib.instance.api.crateApiAddLibraryFolder(dbPath: dbPath, path: path);

/// 移除音乐库文件夹及其后代歌曲。
Future<void> removeLibraryFolder({
  required String dbPath,
  required String path,
}) => RustLib.instance.api.crateApiRemoveLibraryFolder(
  dbPath: dbPath,
  path: path,
);

/// 读取全部本地曲库歌曲（返回 `LibrarySong[]` JSON）。
Future<String> getLibrarySongsCached({required String dbPath}) =>
    RustLib.instance.api.crateApiGetLibrarySongsCached(dbPath: dbPath);

/// 按路径批量查询歌曲（返回 `LibrarySong[]` JSON）。
Future<String> getLibrarySongsByPaths({
  required String dbPath,
  required List<String> paths,
}) => RustLib.instance.api.crateApiGetLibrarySongsByPaths(
  dbPath: dbPath,
  paths: paths,
);

/// 搜索本地音乐库（返回 `LibrarySong[]` JSON）。
Future<String> searchLibrarySongs({
  required String dbPath,
  required String query,
  BigInt? limit,
}) => RustLib.instance.api.crateApiSearchLibrarySongs(
  dbPath: dbPath,
  query: query,
  limit: limit,
);

/// 读取歌手目录（返回 `ArtistCatalogItem[]` JSON）。
Future<String> getLibraryArtistCatalog({required String dbPath}) =>
    RustLib.instance.api.crateApiGetLibraryArtistCatalog(dbPath: dbPath);

/// 读取专辑目录（返回 `AlbumCatalogItem[]` JSON）。
Future<String> getLibraryAlbumCatalog({required String dbPath}) =>
    RustLib.instance.api.crateApiGetLibraryAlbumCatalog(dbPath: dbPath);

/// 按歌手名获取歌曲路径列表。
Future<String> getLibrarySongPathsByArtist({
  required String dbPath,
  required String artistName,
}) => RustLib.instance.api.crateApiGetLibrarySongPathsByArtist(
  dbPath: dbPath,
  artistName: artistName,
);

/// 按专辑 key 获取歌曲路径列表。
Future<String> getLibrarySongPathsByAlbum({
  required String dbPath,
  required String albumKey,
}) => RustLib.instance.api.crateApiGetLibrarySongPathsByAlbum(
  dbPath: dbPath,
  albumKey: albumKey,
);

/// 全部歌曲视图的路径列表（支持查询/歌手/专辑过滤与排序）。
///
/// - `sort_mode`：`"title"`/`"artist"`/`"addedAt"`/`"addedAtAsc"`/
///   `"fileModifiedAt"`/`"fileModifiedAtAsc"`
Future<String> getLibrarySongPathsForAllView({
  required String dbPath,
  String? query,
  String? artistFilter,
  String? albumFilter,
  required String sortMode,
}) => RustLib.instance.api.crateApiGetLibrarySongPathsForAllView(
  dbPath: dbPath,
  query: query,
  artistFilter: artistFilter,
  albumFilter: albumFilter,
  sortMode: sortMode,
);

/// 文件夹视图的歌曲路径列表（支持查询过滤与排序）。
///
/// - `sort_mode`：`"title"`/`"name"`/`"artist"`/`"addedAt"`/`"addedAtAsc"`/`"trackNumber"`
Future<String> getLibrarySongPathsForFolderView({
  required String dbPath,
  required String folderPath,
  String? query,
  required String sortMode,
}) => RustLib.instance.api.crateApiGetLibrarySongPathsForFolderView(
  dbPath: dbPath,
  folderPath: folderPath,
  query: query,
  sortMode: sortMode,
);

/// 扫描所有音乐库文件夹并返回全部歌曲（返回 `LibrarySong[]` JSON）。
Future<String> scanLibrary({
  required String dbPath,
  int? minimumDurationSeconds,
}) => RustLib.instance.api.crateApiScanLibrary(
  dbPath: dbPath,
  minimumDurationSeconds: minimumDurationSeconds,
);

/// 递归构建音乐库文件夹目录树（返回 `FolderNode[]` JSON）。
Future<String> getLibraryHierarchy({required String dbPath}) =>
    RustLib.instance.api.crateApiGetLibraryHierarchy(dbPath: dbPath);

/// 列出指定文件夹的直接子目录节点（返回 `FolderNode[]` JSON）。
Future<String> getFolderChildren({
  required String dbPath,
  required String folderPath,
}) => RustLib.instance.api.crateApiGetFolderChildren(
  dbPath: dbPath,
  folderPath: folderPath,
);

/// 获取歌曲缩略图封面（远程 URI 先缓存到本地），返回缓存路径字符串。
Future<String> getSongCoverThumbnail({
  required String dbPath,
  required String cacheRoot,
  required String path,
}) => RustLib.instance.api.crateApiGetSongCoverThumbnail(
  dbPath: dbPath,
  cacheRoot: cacheRoot,
  path: path,
);

/// 获取歌曲高清封面（远程 URI 先缓存到本地），返回缓存路径字符串。
Future<String> getSongCover({
  required String dbPath,
  required String cacheRoot,
  required String path,
}) => RustLib.instance.api.crateApiGetSongCover(
  dbPath: dbPath,
  cacheRoot: cacheRoot,
  path: path,
);

/// 后台清理封面缓存（超过 4GB 时按访问时间淘汰最旧文件）。
Future<void> runCoverCacheCleanup({required String cacheRoot}) =>
    RustLib.instance.api.crateApiRunCoverCacheCleanup(cacheRoot: cacheRoot);

/// 清空封面缓存目录。
Future<void> clearCoverCache({required String cacheRoot}) =>
    RustLib.instance.api.crateApiClearCoverCache(cacheRoot: cacheRoot);

/// 保存自动提取的歌手头像字节到封面目录，返回规范化路径。
Future<String> saveArtistAvatarAuto({
  required List<int> bytes,
  required String coversRoot,
}) => RustLib.instance.api.crateApiSaveArtistAvatarAuto(
  bytes: bytes,
  coversRoot: coversRoot,
);

/// 读取歌曲歌词（内嵌优先，其次侧边 LRC；远程先查缓存/远程 LRC）。
Future<String> getSongLyrics({required String dbPath, required String path}) =>
    RustLib.instance.api.crateApiGetSongLyrics(dbPath: dbPath, path: path);

/// 读取并解析歌曲歌词（返回 `StructuredLyricsPayload` JSON）。
Future<String> getSongLyricsPayload({
  required String dbPath,
  required String path,
}) => RustLib.instance.api.crateApiGetSongLyricsPayload(
  dbPath: dbPath,
  path: path,
);

/// 读取用户选择的 LRC 文件（自动解码 UTF-8/UTF-16/GBK）。
Future<String> readLyricsFile({required String path}) =>
    RustLib.instance.api.crateApiReadLyricsFile(path: path);

/// 读取歌曲歌词用于编辑（返回 `SongLyricsForEdit` JSON）。
Future<String> getSongLyricsForEdit({required String path}) =>
    RustLib.instance.api.crateApiGetSongLyricsForEdit(path: path);

/// 保存歌曲歌词（内嵌或侧边 LRC），返回 `SongLyricsForEdit` JSON。
Future<String> saveSongLyrics({
  required String path,
  required String lyrics,
  required LyricsStorageSource source,
  String? sourcePath,
}) => RustLib.instance.api.crateApiSaveSongLyrics(
  path: path,
  lyrics: lyrics,
  source: source,
  sourcePath: sourcePath,
);

/// 保存歌曲信息标签（返回 `SaveSongInfoResponse` JSON）。
Future<String> saveSongInfo({
  required String dbPath,
  required String path,
  required String payloadJson,
}) => RustLib.instance.api.crateApiSaveSongInfo(
  dbPath: dbPath,
  path: path,
  payloadJson: payloadJson,
);

/// 保存歌曲背景图（返回存储路径）。
Future<String> saveSongBackground({
  required String dbPath,
  required String dataRoot,
  required String songPath,
  required String backgroundPath,
}) => RustLib.instance.api.crateApiSaveSongBackground(
  dbPath: dbPath,
  dataRoot: dataRoot,
  songPath: songPath,
  backgroundPath: backgroundPath,
);

/// 读取歌曲背景图路径。
Future<String?> getSongBackground({
  required String dbPath,
  required String songPath,
}) => RustLib.instance.api.crateApiGetSongBackground(
  dbPath: dbPath,
  songPath: songPath,
);

/// 清除歌曲背景图。
Future<void> clearSongBackground({
  required String dbPath,
  required String dataRoot,
  required String songPath,
}) => RustLib.instance.api.crateApiClearSongBackground(
  dbPath: dbPath,
  dataRoot: dataRoot,
  songPath: songPath,
);

/// 读取歌曲详情（返回 `SongDetail` JSON）。
Future<String> getSongDetail({required String dbPath, required String path}) =>
    RustLib.instance.api.crateApiGetSongDetail(dbPath: dbPath, path: path);

/// 批量移动歌曲文件并同步数据库（返回 `BatchMoveMusicFilesResult` JSON）。
Future<String> batchMoveMusicFiles({
  required String dbPath,
  required List<String> paths,
  required String targetFolder,
}) => RustLib.instance.api.crateApiBatchMoveMusicFiles(
  dbPath: dbPath,
  paths: paths,
  targetFolder: targetFolder,
);

/// 移动单个歌曲文件并同步数据库。
Future<void> moveMusicFile({
  required String dbPath,
  required String oldPath,
  required String newPath,
}) => RustLib.instance.api.crateApiMoveMusicFile(
  dbPath: dbPath,
  oldPath: oldPath,
  newPath: newPath,
);

/// 在系统文件管理器中定位文件。
Future<void> showInFolder({required String path}) =>
    RustLib.instance.api.crateApiShowInFolder(path: path);

/// 删除音乐文件。
Future<void> deleteMusicFile({required String path}) =>
    RustLib.instance.api.crateApiDeleteMusicFile(path: path);

/// 删除文件夹（递归）。
Future<void> deleteFolder({required String path}) =>
    RustLib.instance.api.crateApiDeleteFolder(path: path);

/// 创建文件夹，返回规范化新路径。
Future<String> createFolder({
  required String parentPath,
  required String folderName,
}) => RustLib.instance.api.crateApiCreateFolder(
  parentPath: parentPath,
  folderName: folderName,
);

/// 移动文件到目标文件夹并同步数据库。
Future<void> moveFileToFolder({
  required String dbPath,
  required String sourcePath,
  required String targetFolder,
}) => RustLib.instance.api.crateApiMoveFileToFolder(
  dbPath: dbPath,
  sourcePath: sourcePath,
  targetFolder: targetFolder,
);

/// 判断路径是否为目录。
Future<bool> isDirectory({required String path}) =>
    RustLib.instance.api.crateApiIsDirectory(path: path);

/// 保存歌手头像（可选写入歌曲标签），返回 `SaveArtistAvatarResponse` JSON。
Future<String> saveArtistAvatar({
  required String dbPath,
  required String coversRoot,
  required PlatformInt64 artistId,
  required String imagePath,
  required bool writeToTags,
}) => RustLib.instance.api.crateApiSaveArtistAvatar(
  dbPath: dbPath,
  coversRoot: coversRoot,
  artistId: artistId,
  imagePath: imagePath,
  writeToTags: writeToTags,
);

/// 保存完整播放会话状态（写入内存 + SQLite）。
Future<void> savePlaybackSession({
  required String dbPath,
  required String sessionJson,
}) => RustLib.instance.api.crateApiSavePlaybackSession(
  dbPath: dbPath,
  sessionJson: sessionJson,
);

/// 获取当前播放会话状态（内存权威），返回 `PlaybackSessionData` JSON。
Future<String> getPlaybackSession() =>
    RustLib.instance.api.crateApiGetPlaybackSession();

/// 从 SQLite 加载播放会话到内存，返回 `PlaybackSessionData` JSON。
Future<String> loadPlaybackSession({required String dbPath}) =>
    RustLib.instance.api.crateApiLoadPlaybackSession(dbPath: dbPath);

/// 高频更新播放进度（防抖写 SQLite）。
Future<void> updatePlaybackPosition({
  required String dbPath,
  required double positionSecs,
  required bool isPlaying,
}) => RustLib.instance.api.crateApiUpdatePlaybackPosition(
  dbPath: dbPath,
  positionSecs: positionSecs,
  isPlaying: isPlaying,
);

/// 强制将内存播放会话持久化到 SQLite。
Future<void> flushPlaybackSession({required String dbPath}) =>
    RustLib.instance.api.crateApiFlushPlaybackSession(dbPath: dbPath);

/// 获取可视化频谱原始采样（返回 `f32[]` JSON）。
Future<String> getVisualizerSnapshot() =>
    RustLib.instance.api.crateApiGetVisualizerSnapshot();

/// 向全局可视化器写入一个 PCM 采样（Flutter 播放线程调用）。
Future<void> pushVisualizerSample({required double sample}) =>
    RustLib.instance.api.crateApiPushVisualizerSample(sample: sample);

/// 重置全局可视化器。
Future<void> resetVisualizer() =>
    RustLib.instance.api.crateApiResetVisualizer();

/// 预览批量重命名（返回 `RenamePreview[]` JSON）。
///
/// - `config_json`：[`RenameConfig`] 的 JSON（camelCase，含 `mode`/`template`/
///   `removeTrackPrefix`/`removeSourcePrefix`）
Future<String> previewRename({
  required String rootPath,
  required String configJson,
}) => RustLib.instance.api.crateApiPreviewRename(
  rootPath: rootPath,
  configJson: configJson,
);

/// 执行批量重命名（返回成功数）。
///
/// - `operations_json`：[`RenameOperation`] 数组的 JSON（camelCase，含 `originalPath`/`newName`）
Future<int> applyRename({required String operationsJson}) =>
    RustLib.instance.api.crateApiApplyRename(operationsJson: operationsJson);

/// 刷新指定文件夹歌曲（增量扫描并写库，返回该文件夹全部歌曲 JSON）。
Future<String> refreshFolderSongs({
  required String dbPath,
  required String folderPath,
  int? minimumDurationSeconds,
}) => RustLib.instance.api.crateApiRefreshFolderSongs(
  dbPath: dbPath,
  folderPath: folderPath,
  minimumDurationSeconds: minimumDurationSeconds,
);

/// 判断路径是否为存在的文件。
Future<bool> fileExists({required String path}) =>
    RustLib.instance.api.crateApiFileExists(path: path);

/// 在目标目录解析非冲突下载文件路径（已存在时自动追加 ` (1)`/` (2)`…）。
Future<String> resolveDownloadPath({
  required String directory,
  required String fileName,
  required bool overwriteExisting,
}) => RustLib.instance.api.crateApiResolveDownloadPath(
  directory: directory,
  fileName: fileName,
  overwriteExisting: overwriteExisting,
);

/// 根据歌曲信息构建下载文件名并解析非冲突完整路径（单次调用）。
Future<String> resolveDownloadFullPath({
  required String directory,
  required String title,
  required String artist,
  required String album,
  required String url,
  required String quality,
  required bool keepSourceFilename,
  required String fileNameStyle,
  required bool overwriteExisting,
}) => RustLib.instance.api.crateApiResolveDownloadFullPath(
  directory: directory,
  title: title,
  artist: artist,
  album: album,
  url: url,
  quality: quality,
  keepSourceFilename: keepSourceFilename,
  fileNameStyle: fileNameStyle,
  overwriteExisting: overwriteExisting,
);

/// 构建下载附件（歌词/封面）的清洗后文件名基名（不含扩展名）。
Future<String> buildDownloadBasename({
  required String title,
  required String artist,
  required String album,
  required String fileNameStyle,
}) => RustLib.instance.api.crateApiBuildDownloadBasename(
  title: title,
  artist: artist,
  album: album,
  fileNameStyle: fileNameStyle,
);

/// 启动 USB 独占播放。返回设备名或错误信息。
/// `device_id` = AAudio 设备 ID（USB DAC），-1 = 默认设备。
Future<String> startUsbExclusivePlayback({
  required String path,
  required int deviceId,
  required double volume,
  required double startTimeSecs,
  required bool isPlaying,
  required double volumeBalanceGain,
  required String equalizerSettingsJson,
  required String soundEffectSettingsJson,
}) => RustLib.instance.api.crateApiStartUsbExclusivePlayback(
  path: path,
  deviceId: deviceId,
  volume: volume,
  startTimeSecs: startTimeSecs,
  isPlaying: isPlaying,
  volumeBalanceGain: volumeBalanceGain,
  equalizerSettingsJson: equalizerSettingsJson,
  soundEffectSettingsJson: soundEffectSettingsJson,
);

/// 停止 USB 独占播放并释放设备。
Future<void> stopUsbExclusivePlayback() =>
    RustLib.instance.api.crateApiStopUsbExclusivePlayback();

/// 跳转到指定位置（秒）。
Future<void> seekUsbExclusive({
  required double timeSecs,
  required bool isPlaying,
}) => RustLib.instance.api.crateApiSeekUsbExclusive(
  timeSecs: timeSecs,
  isPlaying: isPlaying,
);

/// 设置用户音量（0.0–1.0）。
Future<void> setUsbExclusiveVolume({required double volume}) =>
    RustLib.instance.api.crateApiSetUsbExclusiveVolume(volume: volume);

/// 更新 EQ 设置（camelCase JSON）。
Future<void> setUsbExclusiveEqualizer({required String settingsJson}) => RustLib
    .instance
    .api
    .crateApiSetUsbExclusiveEqualizer(settingsJson: settingsJson);

/// 更新音效设置（camelCase JSON）。
Future<void> setUsbExclusiveSoundEffect({required String settingsJson}) =>
    RustLib.instance.api.crateApiSetUsbExclusiveSoundEffect(
      settingsJson: settingsJson,
    );

/// USB 独占播放是否活跃。
Future<bool> isUsbExclusiveActive() =>
    RustLib.instance.api.crateApiIsUsbExclusiveActive();

/// 获取当前播放位置（秒）。
Future<double> getUsbExclusivePositionSecs() =>
    RustLib.instance.api.crateApiGetUsbExclusivePositionSecs();

/// 获取当前播放采样率。
Future<int> getUsbExclusiveSampleRate() =>
    RustLib.instance.api.crateApiGetUsbExclusiveSampleRate();

/// 获取当前声道数。
Future<int> getUsbExclusiveChannels() =>
    RustLib.instance.api.crateApiGetUsbExclusiveChannels();

/// 检查 GitHub Release 最新版本（返回原始 JSON）。
Future<String> checkUpdateByRust({
  required String owner,
  required String repo,
}) => RustLib.instance.api.crateApiCheckUpdateByRust(owner: owner, repo: repo);

/// 下载在线歌曲真实音源直链到指定路径（流式写入 + QMC2 解密），返回最终路径。
///
/// - `headers_json`：可选 HTTP 头 JSON（对象）
/// - `ekey`：可选 QMC2 加密 key（base64）
Future<String> downloadOnlineSong({
  required String url,
  required String destPath,
  String? ekey,
  required String headersJson,
}) => RustLib.instance.api.crateApiDownloadOnlineSong(
  url: url,
  destPath: destPath,
  ekey: ekey,
  headersJson: headersJson,
);

/// 原地解密 QMC2 加密文件，返回是否解密成功。
Future<bool> decryptQmcFile({required String filePath, String? ekey}) =>
    RustLib.instance.api.crateApiDecryptQmcFile(filePath: filePath, ekey: ekey);

/// 保存歌词文本到指定文件（自动创建父目录），返回规范化路径。
Future<String> saveDownloadLyrics({
  required String content,
  required String destPath,
}) => RustLib.instance.api.crateApiSaveDownloadLyrics(
  content: content,
  destPath: destPath,
);

/// 将文本内容写入指定路径（自动创建父目录），返回规范化路径。
Future<String> writeTextFile({
  required String content,
  required String destPath,
}) => RustLib.instance.api.crateApiWriteTextFile(
  content: content,
  destPath: destPath,
);

/// 通过 reqwest 下载图片二进制（返回 `{"data":[...],"mime":"..."}` JSON）。
Future<String> fetchImageBytes({required String url}) =>
    RustLib.instance.api.crateApiFetchImageBytes(url: url);

/// 将前端已下载的字节数据写入目标文件，返回规范化路径。
Future<String> saveDownloadBytes({
  required List<int> data,
  required String destPath,
}) => RustLib.instance.api.crateApiSaveDownloadBytes(
  data: data,
  destPath: destPath,
);

/// 将歌曲元数据写入音频文件 tag。
///
/// - `request_json`：[`EmbedMetadataRequest`] 的 JSON（camelCase，含 `filePath` 及可选字段）
Future<void> embedAudioMetadata({required String requestJson}) =>
    RustLib.instance.api.crateApiEmbedAudioMetadata(requestJson: requestJson);

/// 下载后收尾编排：歌词保存 + 封面下载保存 + 元数据嵌入。
///
/// - `request_json`：[`FinalizeDownloadExtrasRequest`] 的 JSON（camelCase）
///
/// 返回 [`FinalizeDownloadExtrasResult`] JSON（camelCase）。
Future<String> finalizeDownloadExtras({required String requestJson}) => RustLib
    .instance
    .api
    .crateApiFinalizeDownloadExtras(requestJson: requestJson);

/// 读取下载记录 JSON 文本（文件不存在或损坏时返回 `"{}"`）。
Future<String> readDownloadHistory({required String dataDir}) =>
    RustLib.instance.api.crateApiReadDownloadHistory(dataDir: dataDir);

/// 写入下载记录 JSON 文本（整体覆盖，自动创建父目录）。
Future<void> writeDownloadHistory({
  required String dataDir,
  required String content,
}) => RustLib.instance.api.crateApiWriteDownloadHistory(
  dataDir: dataDir,
  content: content,
);

/// 用 `Range: bytes=0-0` 探测直链文件大小（返回 `ProbeUrlInfo` JSON）。
Future<String> probeUrlSize({required String url}) =>
    RustLib.instance.api.crateApiProbeUrlSize(url: url);

/// 获取公告（返回解析出的 data JSON 字符串）。
Future<String> fetchAnnouncement() =>
    RustLib.instance.api.crateApiFetchAnnouncement();

/// 将 JSON 字符串写入 `{data_dir}/state/{key}.json`。
Future<void> writeStateJson({
  required String dataDir,
  required String key,
  required String value,
}) => RustLib.instance.api.crateApiWriteStateJson(
  dataDir: dataDir,
  key: key,
  value: value,
);

/// 从 `{data_dir}/state/{key}.json` 读取 JSON 字符串（不存在返回 null）。
Future<String?> readStateJson({required String dataDir, required String key}) =>
    RustLib.instance.api.crateApiReadStateJson(dataDir: dataDir, key: key);

/// 异步 HTTP 请求（返回 `PluginHttpResponse` JSON：`status`/`url`/`headers`/`body`）。
Future<String> pluginHttpRequest({
  required String method,
  required String url,
  required String headersJson,
  String? body,
  BigInt? timeout,
  int? follow,
}) => RustLib.instance.api.crateApiPluginHttpRequest(
  method: method,
  url: url,
  headersJson: headersJson,
  body: body,
  timeout: timeout,
  follow: follow,
);

/// 异步二进制 HTTP 请求（返回 `PluginHttpBinaryResponse` JSON，body 为 base64）。
Future<String> pluginHttpRequestBinary({
  required String method,
  required String url,
  required String headersJson,
  String? body,
  BigInt? timeout,
  int? follow,
}) => RustLib.instance.api.crateApiPluginHttpRequestBinary(
  method: method,
  url: url,
  headersJson: headersJson,
  body: body,
  timeout: timeout,
  follow: follow,
);

/// 读取插件/文本文件内容（限 `.js/.json/.txt/.m3u/.m3u8`）。
Future<String> readPluginFile({required String path}) =>
    RustLib.instance.api.crateApiReadPluginFile(path: path);

/// 将插件脚本保存到 `{data_dir}/plugins/{id}.js`，返回保存后的完整路径。
Future<String> savePluginScript({
  required String dataDir,
  required String id,
  required String script,
}) => RustLib.instance.api.crateApiSavePluginScript(
  dataDir: dataDir,
  id: id,
  script: script,
);

/// 读取本地文件二进制内容（base64 编码返回，限 `.json/.zip/.lxmc`）。
Future<String> readFileBytes({required String path}) =>
    RustLib.instance.api.crateApiReadFileBytes(path: path);

/// 代理图片请求（自动添加 Referer，返回 data URL）。
Future<String> proxyImage({required String url, String? referer}) =>
    RustLib.instance.api.crateApiProxyImage(url: url, referer: referer);

/// 异步下载音频到临时文件，返回本地文件路径。
Future<String> downloadAudioToTemp({
  required String url,
  required String headersJson,
}) => RustLib.instance.api.crateApiDownloadAudioToTemp(
  url: url,
  headersJson: headersJson,
);

/// 取消正在进行的音频识别。
Future<void> cancelRecognizeSystemAudio() =>
    RustLib.instance.api.crateApiCancelRecognizeSystemAudio();

/// 使用自定义 PCM 数据识别歌曲（8000Hz/16bit/单声道），返回 `RecognizeResponse` JSON。
Future<String> recognizeWithPcm({required List<int> pcm}) =>
    RustLib.instance.api.crateApiRecognizeWithPcm(pcm: pcm);

/// 导入歌词字体，返回 `ImportedLyricsFont` JSON（camelCase）。
Future<String> importLyricsFont({
  required String dataRoot,
  required String sourcePath,
}) => RustLib.instance.api.crateApiImportLyricsFont(
  dataRoot: dataRoot,
  sourcePath: sourcePath,
);

/// 读取已导入歌词字体为 data URL。
Future<String> readLyricsFontDataUrl({
  required String dataRoot,
  required String fontPath,
}) => RustLib.instance.api.crateApiReadLyricsFontDataUrl(
  dataRoot: dataRoot,
  fontPath: fontPath,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BufferedMonitorHandle>>
abstract class BufferedMonitorHandle implements RustOpaqueInterface {
  /// 自上次调用以来是否已补充缓冲（读取后清除）。
  Future<bool> consumeProduced();

  static Future<BufferedMonitorHandle> default_() =>
      RustLib.instance.api.crateApiBufferedMonitorHandleDefault();

  /// 是否处于缓冲饥饿状态（消费线程取不到样本块）。
  Future<bool> isStarved();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// 创建新的监控句柄。
  static Future<BufferedMonitorHandle> newInstance() =>
      RustLib.instance.api.crateApiBufferedMonitorHandleNew();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EqualizerProcessor>>
abstract class EqualizerProcessor implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// 创建均衡器。`channels` 为 1 或 2。
  static Future<EqualizerProcessor> newInstance({
    required int sampleRate,
    required int channels,
  }) => RustLib.instance.api.crateApiEqualizerProcessorNew(
    sampleRate: sampleRate,
    channels: channels,
  );

  /// 处理一块交错 PCM，返回处理后的交错 PCM。
  Future<Float32List> processBlock({required List<double> samples});

  /// seek 时调用，清空滤波器状态防 click。
  Future<void> reset();

  /// 设置均衡器参数（camelCase JSON：`{"enabled":bool,"preamp":dB,"gains":[10个dB]}`）。
  Future<void> setSettings({required String settingsJson});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SoundEffectProcessor>>
abstract class SoundEffectProcessor implements RustOpaqueInterface {
  /// 当前实际（可能被变速改变的）采样率。
  Future<int> effectiveSampleRate();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// 创建处理器。`channels` 为 1 或 2。
  static Future<SoundEffectProcessor> newInstance({
    required int sampleRate,
    required int channels,
  }) => RustLib.instance.api.crateApiSoundEffectProcessorNew(
    sampleRate: sampleRate,
    channels: channels,
  );

  /// 处理一块交错 PCM，返回处理后的交错 PCM。
  Future<Float32List> processBlock({required List<double> samples});

  /// 清空内部延时/混响/包络状态。
  Future<void> reset();

  /// 设置音效参数（camelCase JSON，可部分省略）。
  Future<void> setSettings({required String settingsJson});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VolumeNormalizerProcessor>>
abstract class VolumeNormalizerProcessor implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// 创建处理器。`channels` 为 1 或 2；`initialGain` 为起始 Linear Gain；
  /// `rampMs` 为增益渐变时间（毫秒）。
  static Future<VolumeNormalizerProcessor> newInstance({
    required int sampleRate,
    required int channels,
    required double initialGain,
    required int rampMs,
  }) => RustLib.instance.api.crateApiVolumeNormalizerProcessorNew(
    sampleRate: sampleRate,
    channels: channels,
    initialGain: initialGain,
    rampMs: rampMs,
  );

  /// 处理一块交错 PCM，返回乘以逐帧渐增增益后的交错 PCM。
  Future<Float32List> processBlock({required List<double> samples});

  /// 重置增益渐变状态。
  Future<void> reset();
}
