// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

export 'api.dart';

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 对一整块 QMC 加密音频字节做解密，返回解密后的字节。
/// `ekey` 为 base64 编码的 QMC2 key（EncV2 已自动处理）。
Future<Uint8List> qmcDecryptBytes({
  required List<int> data,
  required String ekey,
}) => RustLib.instance.api.crateApiQmcDecryptBytes(data: data, ekey: ekey);

/// 将 PCM 采样划分成指定数量的频带，返回每个频带的归一化能量。
Future<Float32List> spectrumBands({
  required List<double> samples,
  required int sampleRate,
  required BigInt bandCount,
}) => RustLib.instance.api.crateApiSpectrumBands(
  samples: samples,
  sampleRate: sampleRate,
  bandCount: bandCount,
);
