// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_cue_bytes`, `extract_file_directive`, `extract_index01`, `extract_quoted`, `extract_track_number`, `into_cue_track`, `parse_cue_content`, `parse_cue_timestamp`, `resolve_audio_path`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CueTrackBuilder`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `source`

Future<CueSheet> parseCueFile({required Path cuePath}) =>
    RustLib.instance.api.crateMusicCueParseCueFile(cuePath: cuePath);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CueParseError>>
abstract class CueParseError implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CueSheet>>
abstract class CueSheet implements RustOpaqueInterface {
  String? get albumPerformer;

  String? get albumTitle;

  String get filePath;

  PathBuf get resolvedAudioPath;

  List<CueTrack> get tracks;

  set albumPerformer(String? albumPerformer);

  set albumTitle(String? albumTitle);

  set filePath(String filePath);

  set resolvedAudioPath(PathBuf resolvedAudioPath);

  set tracks(List<CueTrack> tracks);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Path>>
abstract class Path implements RustOpaqueInterface {}

class CueTrack {
  final int trackNumber;
  final String? title;
  final String? performer;
  final BigInt index01StartMs;
  final BigInt? endMs;

  const CueTrack({
    required this.trackNumber,
    this.title,
    this.performer,
    required this.index01StartMs,
    this.endMs,
  });

  @override
  int get hashCode =>
      trackNumber.hashCode ^
      title.hashCode ^
      performer.hashCode ^
      index01StartMs.hashCode ^
      endMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CueTrack &&
          runtimeType == other.runtimeType &&
          trackNumber == other.trackNumber &&
          title == other.title &&
          performer == other.performer &&
          index01StartMs == other.index01StartMs &&
          endMs == other.endMs;
}
