// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'cue.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clean_text`, `copy_preferred_id3v2_text`, `decode_id3v2_text_frame`, `decode_riff_info_text`, `decode_utf16_be`, `decode_utf16_le`, `decode_utf16_with_bom`, `guess_tag_type_from_path`, `has_wav_header`, `id3v2_text_frame_key`, `insert_optional_text`, `is_bad_timestamp_error`, `is_mpeg_path`, `is_wav_path`, `item_text`, `leading_id3v2_size`, `lofty_tag_from_id3`, `looks_like_lyrics_description`, `looks_like_lyrics_key`, `ordered_tags`, `parse_riff_info_list`, `parse_u32_field`, `parse_wav_chunks`, `prefer_leading_id3v2_text`, `push_id3_tag`, `push_unique_tag`, `read_album_artist`, `read_album`, `read_artist`, `read_chunk`, `read_leading_id3_tag`, `read_leading_id3v2_text_tag`, `read_salvaged_id3_tags`, `read_salvaged_wav_tags`, `read_tag_text`, `read_tagged_file_from_path_with_cover_mode`, `read_title`, `seems_like_lyrics_text`, `skip_chunk`, `skip_id3v2_extended_header`, `syncsafe_u32`
// These functions are ignored because they have generic arguments: `extract_detail_metadata`, `extract_embedded_lyrics_match`, `extract_embedded_lyrics`, `extract_text_metadata`, `find_embedded_artist_picture`, `find_embedded_picture`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

Future<TaggedFile> readTaggedFileFromPath({required Path path}) =>
    RustLib.instance.api.crateMusicTagsReadTaggedFileFromPath(path: path);

Future<TaggedFile> readTaggedFileFromPathForScan({required Path path}) =>
    RustLib.instance.api.crateMusicTagsReadTaggedFileFromPathForScan(
      path: path,
    );

Future<bool> containsLrcTimestamp({required String text}) =>
    RustLib.instance.api.crateMusicTagsContainsLrcTimestamp(text: text);

/// 将元数据写入音频文件的 tag（ID3v2/Vorbis Comment/MP4 Atom 等）。
///
/// 仅写入请求中提供的非空字段；已有的其他字段保持不变。
/// 若文件无现有 tag，则按扩展名推断 tag 类型后创建。
Future<void> writeMetadataToFile({required EmbedMetadataRequest request}) =>
    RustLib.instance.api.crateMusicTagsWriteMetadataToFile(request: request);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EmbeddedLyricsMatch>>
abstract class EmbeddedLyricsMatch implements RustOpaqueInterface {
  String get description;

  ItemKey get itemKey;

  TagType get tagType;

  String get text;

  set description(String description);

  set itemKey(ItemKey itemKey);

  set tagType(TagType tagType);

  set text(String text);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TaggedFile>>
abstract class TaggedFile implements RustOpaqueInterface {}

/// 元数据嵌入请求：将歌曲元数据写入音频文件 tag。
///
/// 所有字段均为可选，仅写入提供的非空字段。
/// `cover_data` 为封面二进制数据，`cover_mime` 标识 MIME 类型（默认 image/jpeg）。
class EmbedMetadataRequest {
  final String filePath;
  final String? title;
  final String? artist;
  final String? album;
  final String? albumArtist;
  final String? year;
  final String? trackNumber;
  final String? discNumber;
  final String? lyrics;
  final Uint8List? coverData;
  final String? coverMime;

  const EmbedMetadataRequest({
    required this.filePath,
    this.title,
    this.artist,
    this.album,
    this.albumArtist,
    this.year,
    this.trackNumber,
    this.discNumber,
    this.lyrics,
    this.coverData,
    this.coverMime,
  });

  static Future<EmbedMetadataRequest> default_() =>
      RustLib.instance.api.crateMusicTagsEmbedMetadataRequestDefault();

  @override
  int get hashCode =>
      filePath.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      albumArtist.hashCode ^
      year.hashCode ^
      trackNumber.hashCode ^
      discNumber.hashCode ^
      lyrics.hashCode ^
      coverData.hashCode ^
      coverMime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmbedMetadataRequest &&
          runtimeType == other.runtimeType &&
          filePath == other.filePath &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          albumArtist == other.albumArtist &&
          year == other.year &&
          trackNumber == other.trackNumber &&
          discNumber == other.discNumber &&
          lyrics == other.lyrics &&
          coverData == other.coverData &&
          coverMime == other.coverMime;
}

class TagDetailMetadata {
  final String? genre;
  final String? year;
  final String? trackNumber;
  final String? discNumber;
  final String? comment;

  const TagDetailMetadata({
    this.genre,
    this.year,
    this.trackNumber,
    this.discNumber,
    this.comment,
  });

  static Future<TagDetailMetadata> default_() =>
      RustLib.instance.api.crateMusicTagsTagDetailMetadataDefault();

  @override
  int get hashCode =>
      genre.hashCode ^
      year.hashCode ^
      trackNumber.hashCode ^
      discNumber.hashCode ^
      comment.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagDetailMetadata &&
          runtimeType == other.runtimeType &&
          genre == other.genre &&
          year == other.year &&
          trackNumber == other.trackNumber &&
          discNumber == other.discNumber &&
          comment == other.comment;
}

class TagTextMetadata {
  final String? title;
  final String? artist;
  final String? album;
  final String? albumArtist;

  const TagTextMetadata({
    this.title,
    this.artist,
    this.album,
    this.albumArtist,
  });

  static Future<TagTextMetadata> default_() =>
      RustLib.instance.api.crateMusicTagsTagTextMetadataDefault();

  @override
  int get hashCode =>
      title.hashCode ^ artist.hashCode ^ album.hashCode ^ albumArtist.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagTextMetadata &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          albumArtist == other.albumArtist;
}
