// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clamp_i64_to_u32`, `i64_to_bool`, `i64_to_u64_opt`, `i64_to_u8_opt`

Future<String> normalizePath({required String pathStr}) =>
    RustLib.instance.api.crateMusicUtilsNormalizePath(pathStr: pathStr);

/// Escape special characters for SQL LIKE pattern with `ESCAPE '^'`.
Future<String> escapeLike({required String input}) =>
    RustLib.instance.api.crateMusicUtilsEscapeLike(input: input);

/// Build forward/backward descendant LIKE patterns for a folder path.
/// Caller should use:
/// `path = ?1 OR path LIKE ?2 ESCAPE '^' OR path LIKE ?3 ESCAPE '^'`
Future<(String, String)> descendantLikePatterns({required String folderPath}) =>
    RustLib.instance.api.crateMusicUtilsDescendantLikePatterns(
      folderPath: folderPath,
    );

Future<bool> isSupportedLibraryExtension({required String ext}) =>
    RustLib.instance.api.crateMusicUtilsIsSupportedLibraryExtension(ext: ext);

Future<bool> isCueFileExtension({required String ext}) =>
    RustLib.instance.api.crateMusicUtilsIsCueFileExtension(ext: ext);

Future<bool> isLosslessAudio({Str? codec, required String format}) => RustLib
    .instance
    .api
    .crateMusicUtilsIsLosslessAudio(codec: codec, format: format);

Future<void> formatDistributionBucket({
  Str? container,
  Str? codec,
  required String format,
}) => RustLib.instance.api.crateMusicUtilsFormatDistributionBucket(
  container: container,
  codec: codec,
  format: format,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<str>>
abstract class Str implements RustOpaqueInterface {}
