// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import '../music/cue.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `canonicalize_path_or_parent`

/// Validate that a path is safe and within allowed directories.
///
/// # Security
/// - Rejects paths containing `..` components
/// - Canonicalizes the path (resolves symlinks) when possible
/// - Checks the canonical path starts with one of the allowed roots
/// - If no allowed_roots provided, rejects symlink/reparse-point components after basic traversal checks
///
/// # Arguments
/// * `input` - The raw path string from IPC
/// * `allowed_roots` - Optional list of allowed root directories. If None, symlink components are still rejected.
///
/// # Returns
/// * `Ok(PathBuf)` - The validated, canonicalized path
/// * `Err(String)` - Error message describing why validation failed
Future<PathBuf> validatePath({required String input, PathBuf? allowedRoots}) =>
    RustLib.instance.api.crateSecurityPathValidatorValidatePath(
      input: input,
      allowedRoots: allowedRoots,
    );

/// Validate that a path is within a specific directory.
///
/// Convenience wrapper around `validate_path` with a single allowed root.
Future<PathBuf> validatePathInDir({
  required String input,
  required Path allowedRoot,
}) => RustLib.instance.api.crateSecurityPathValidatorValidatePathInDir(
  input: input,
  allowedRoot: allowedRoot,
);

/// Sanitize a filename by removing path separators and dangerous characters.
///
/// This is used when a user-provided string will be used as a filename component.
Future<String> sanitizeFilenameComponent({required String name}) => RustLib
    .instance
    .api
    .crateSecurityPathValidatorSanitizeFilenameComponent(name: name);
