// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'qmc2.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `calc_hash_base`, `calc_segment_key`, `decrypt`, `decrypt`, `derive_tea_key`, `encode_first_segment`, `encode_other_segment`, `find_subslice`, `is_valid_audio_header`, `map_l`, `new`, `new`, `parse_ekey`, `qmc1_get_mask`, `rc4_derive`, `scramble_by_index`, `simple_make_key`, `tc_tea_decrypt`, `tea_decrypt_ecb`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `QmcDecryptReader`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `read`, `seek`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `new`

/// QMC1 in-place decryption (no ekey needed).
Future<void> qmc1Decrypt({required U8 data}) =>
    RustLib.instance.api.cratePlayerQmc2Qmc1Decrypt(data: data);

/// Check if a downloaded file has a QTag or V1 footer with an embedded ekey.
/// Returns the extracted base64-encoded ekey if found.
Future<String?> extractEkeyFromFooter({required List<int> data}) =>
    RustLib.instance.api.cratePlayerQmc2ExtractEkeyFromFooter(data: data);

/// Check if file header looks like QMC-encrypted content (not a valid audio format).
Future<bool> looksLikeQmcEncrypted({required List<int> header}) =>
    RustLib.instance.api.cratePlayerQmc2LooksLikeQmcEncrypted(header: header);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<[u8]>>
abstract class U8 implements RustOpaqueInterface {}

class Qmc2MapCrypto {
  final Uint8List key;

  const Qmc2MapCrypto({required this.key});

  @override
  int get hashCode => key.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Qmc2MapCrypto &&
          runtimeType == other.runtimeType &&
          key == other.key;
}

class Qmc2Rc4Crypto {
  final Uint8List s;
  final int hash;
  final Uint8List rc4Key;

  const Qmc2Rc4Crypto({
    required this.s,
    required this.hash,
    required this.rc4Key,
  });

  @override
  int get hashCode => s.hashCode ^ hash.hashCode ^ rc4Key.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Qmc2Rc4Crypto &&
          runtimeType == other.runtimeType &&
          s == other.s &&
          hash == other.hash &&
          rc4Key == other.rc4Key;
}

class QmcCrypto {
  final QmcCryptoInner inner;

  const QmcCrypto({required this.inner});

  /// Decrypt a buffer at the given file offset.
  Future<void> decrypt({required BigInt offset, required U8 buf}) => RustLib
      .instance
      .api
      .cratePlayerQmc2QmcCryptoDecrypt(that: this, offset: offset, buf: buf);

  /// Create from a base64-encoded ekey (QMC2).
  static Future<QmcCrypto> fromEkey({required String ekey}) =>
      RustLib.instance.api.cratePlayerQmc2QmcCryptoFromEkey(ekey: ekey);

  /// Create QMC1 crypto (no ekey).
  static Future<QmcCrypto> qmc1() =>
      RustLib.instance.api.cratePlayerQmc2QmcCryptoQmc1();

  @override
  int get hashCode => inner.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QmcCrypto &&
          runtimeType == other.runtimeType &&
          inner == other.inner;
}

@freezed
sealed class QmcCryptoInner with _$QmcCryptoInner {
  const QmcCryptoInner._();

  const factory QmcCryptoInner.map(Qmc2MapCrypto field0) = QmcCryptoInner_Map;
  const factory QmcCryptoInner.rc4(Qmc2Rc4Crypto field0) = QmcCryptoInner_Rc4;
  const factory QmcCryptoInner.qmc1() = QmcCryptoInner_Qmc1;
}
